### ISSUE TITLE
[Question] Cannot Initialize Discord SharpPresence

### ISSUE THREAD

**Issue by TimmyRB** [LetsRaceBwoi/DiscordRPCSharp#2]
I'm trying to Initialize Discord but the Discord Docs say to use memset which C# doesn't have (As far as I can tell) to set all the handlers in Initialize Method

My Code looks like this:
```
unsafe void InitDiscord()
    {
        SharpPresence.Discord.EventHandlers handlers;
        handlers.ready = handleDiscordReady();
        handlers.errored = handleDiscordError();
        SharpPresence.Discord.Initialize('CLIENT_ID', &handlers);
    }
```
When using `&handlers` I get 
`cannot convert from 'SharpPresence.Discord.EventHandlers*' to 'SharpPresence.Discord.EventHandlers'`

Any help would be greatly appreciated!

**Comment by xezno** [comment]
You're passing handlers across incorrectly.  You don't need to pass them as a reference - that's handled automatically.  Just do `SharpPresence.Discord.Initialize('CLIENT_ID', handlers);`.

**Comment by TimmyRB** [comment]
I tried that but then I get
`Use of unassigned variable 'handlers' `
